# Generated by Django 4.2.7 on 2025-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.TextField(blank=True, help_text='Explanation of why this track was recommended'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0.0, help_text='Recommendation confidence score (0.0 to 1.0)'),
        ),
    ]
